// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkssxzudwefadbwihcrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrc3N4enVkd2VmYWRid2loY3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMTc3NzUsImV4cCI6MjA2ODg5Mzc3NX0.D5gazzzvaNX0u9brURrkQVzdLJGdPwDaHX1cz2fenQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});